name: Publish on Netlify

on: push

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - folder: explorer
            id: b0717fc8-7b5c-4368-9f29-4893c56b4473
          - folder: sale
            id: c5f3af05-acac-4a0a-a561-52a3ec751962

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - uses: nrwl/last-successful-commit-action@v1
      id: last_successful_commit
      with:
        branch: 'main'
        workflow_id: 'deploy.yml'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "::set-output name=IGNORE::$(git diff --quiet $(git rev-parse --short ${{ steps.last_successful_commit.outputs.commit_hash }}) $(git rev-parse --short ${{ github.sha }}) -- apps/${{ matrix.folder }} lib || echo "true")"
      id: diff

    - uses: actions/setup-node@v3
      if: ${{ steps.diff.outputs.IGNORE == 'true' }}
      with:
        node-version: '16'
        cache: 'yarn'

    - uses: actions/cache@v3
      if: ${{ steps.diff.outputs.IGNORE == 'true' }}
      with:
        path: |
          ${{ github.workspace }}/node_modules/.cache/turbo
          ${{ github.workspace }}/apps/${{ matrix.folder }}/.netlify/cache
        key: ${{ runner.os }}-nextjs-${{ matrix.folder }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('apps/${{ matrix.folder }}/**.[jt]sx?', 'apps/${{ matrix.folder }}/**.json', 'lib/**.[jt]sx?') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.folder }}-${{ hashFiles('**/yarn.lock') }}-

    - run: yarn install --immutable
      if: ${{ steps.diff.outputs.IGNORE == 'true' }}

    - run: yarn deploy:${{ matrix.folder }}
      if: ${{ steps.diff.outputs.IGNORE == 'true' }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ matrix.id }}